// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH7IBQOHsZjdHlhA-Hb8S78Ru8tGLMAUY',
    appId: '1:15307976336:web:77e296797293cf3f473215',
    messagingSenderId: '15307976336',
    projectId: 'koyden-sehire-d3e7c',
    authDomain: 'koyden-sehire-d3e7c.firebaseapp.com',
    storageBucket: 'koyden-sehire-d3e7c.firebasestorage.app',
    measurementId: 'G-L4M7X7KG3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeopau5gRAUiHcVUcILE6OjliUsPQeiqU',
    appId: '1:15307976336:android:f3d14ff52e1e3fa4473215',
    messagingSenderId: '15307976336',
    projectId: 'koyden-sehire-d3e7c',
    storageBucket: 'koyden-sehire-d3e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzRThB4RqoxCb2O7G0h_8sE3sLPTt6ghk',
    appId: '1:15307976336:ios:6ff6e111753c646e473215',
    messagingSenderId: '15307976336',
    projectId: 'koyden-sehire-d3e7c',
    storageBucket: 'koyden-sehire-d3e7c.firebasestorage.app',
    iosBundleId: 'com.koydensehire.koydenSehire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzRThB4RqoxCb2O7G0h_8sE3sLPTt6ghk',
    appId: '1:15307976336:ios:6ff6e111753c646e473215',
    messagingSenderId: '15307976336',
    projectId: 'koyden-sehire-d3e7c',
    storageBucket: 'koyden-sehire-d3e7c.firebasestorage.app',
    iosBundleId: 'com.koydensehire.koydenSehire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH7IBQOHsZjdHlhA-Hb8S78Ru8tGLMAUY',
    appId: '1:15307976336:web:559031738610753c473215',
    messagingSenderId: '15307976336',
    projectId: 'koyden-sehire-d3e7c',
    authDomain: 'koyden-sehire-d3e7c.firebaseapp.com',
    storageBucket: 'koyden-sehire-d3e7c.firebasestorage.app',
    measurementId: 'G-VG7MKKFFK8',
  );

}